# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/creep_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/creep_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n1modules/planning/proto/creep_decider_config.proto\x12\x0f\x61pollo.planning\"\xcc\x01\n\x12\x43reepDeciderConfig\x12\x1a\n\rstop_distance\x18\x01 \x01(\x01:\x03\x30.5\x12\x16\n\x0bspeed_limit\x18\x02 \x01(\x01:\x01\x31\x12$\n\x17max_valid_stop_distance\x18\x03 \x01(\x01:\x03\x30.3\x12\x19\n\x0emin_boundary_t\x18\x04 \x01(\x01:\x01\x36\x12 \n\x13ignore_max_st_min_t\x18\x05 \x01(\x01:\x03\x30.1\x12\x1f\n\x13ignore_min_st_min_s\x18\x06 \x01(\x01:\x02\x31\x35')
)




_CREEPDECIDERCONFIG = _descriptor.Descriptor(
  name='CreepDeciderConfig',
  full_name='apollo.planning.CreepDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stop_distance', full_name='apollo.planning.CreepDeciderConfig.stop_distance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_limit', full_name='apollo.planning.CreepDeciderConfig.speed_limit', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_valid_stop_distance', full_name='apollo.planning.CreepDeciderConfig.max_valid_stop_distance', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_boundary_t', full_name='apollo.planning.CreepDeciderConfig.min_boundary_t', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(6),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ignore_max_st_min_t', full_name='apollo.planning.CreepDeciderConfig.ignore_max_st_min_t', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ignore_min_st_min_s', full_name='apollo.planning.CreepDeciderConfig.ignore_min_st_min_s', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(15),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=275,
)

DESCRIPTOR.message_types_by_name['CreepDeciderConfig'] = _CREEPDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreepDeciderConfig = _reflection.GeneratedProtocolMessageType('CreepDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _CREEPDECIDERCONFIG,
  __module__ = 'modules.planning.proto.creep_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.CreepDeciderConfig)
  ))
_sym_db.RegisterMessage(CreepDeciderConfig)


# @@protoc_insertion_point(module_scope)
