# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/dp_st_speed_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/dp_st_speed_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n/modules/planning/proto/dp_st_speed_config.proto\x12\x0f\x61pollo.planning\"\x9a\x01\n\x14SpeedHeuristicConfig\x12>\n\x14\x64\x65\x66\x61ult_speed_config\x18\x01 \x01(\x0b\x32 .apollo.planning.DpStSpeedConfig\x12\x42\n\x18lane_change_speed_config\x18\x02 \x01(\x0b\x32 .apollo.planning.DpStSpeedConfig\"\xc0\x06\n\x0f\x44pStSpeedConfig\x12\x11\n\x06unit_t\x18\x01 \x01(\x01:\x01\x31\x12\x1d\n\x11\x64\x65nse_dimension_s\x18\x02 \x01(\x05:\x02\x34\x31\x12\x19\n\x0c\x64\x65nse_unit_s\x18\x03 \x01(\x01:\x03\x30.5\x12\x18\n\rsparse_unit_s\x18\x04 \x01(\x01:\x01\x31\x12\x17\n\x0cspeed_weight\x18\n \x01(\x01:\x01\x30\x12\x18\n\x0c\x61\x63\x63\x65l_weight\x18\x0b \x01(\x01:\x02\x31\x30\x12\x17\n\x0bjerk_weight\x18\x0c \x01(\x01:\x02\x31\x30\x12\x1a\n\x0fobstacle_weight\x18\r \x01(\x01:\x01\x31\x12\x1b\n\x10reference_weight\x18\x0e \x01(\x01:\x01\x30\x12\x19\n\x0ego_down_buffer\x18\x0f \x01(\x01:\x01\x35\x12\x17\n\x0cgo_up_buffer\x18\x10 \x01(\x01:\x01\x35\x12*\n\x15\x64\x65\x66\x61ult_obstacle_cost\x18\x14 \x01(\x01:\x0b\x31\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x12\x1d\n\x12\x64\x65\x66\x61ult_speed_cost\x18\x1f \x01(\x01:\x01\x31\x12 \n\x14\x65xceed_speed_penalty\x18  \x01(\x01:\x02\x31\x30\x12\x1e\n\x11low_speed_penalty\x18! \x01(\x01:\x03\x32.5\x12\"\n\x17reference_speed_penalty\x18\" \x01(\x01:\x01\x31\x12(\n\x1ckeep_clear_low_speed_penalty\x18# \x01(\x01:\x02\x31\x30\x12\x18\n\raccel_penalty\x18( \x01(\x01:\x01\x32\x12\x18\n\rdecel_penalty\x18) \x01(\x01:\x01\x32\x12\x1e\n\x13positive_jerk_coeff\x18\x32 \x01(\x01:\x01\x31\x12 \n\x13negative_jerk_coeff\x18\x33 \x01(\x01:\x03\x33\x30\x30\x12\x1d\n\x10max_acceleration\x18< \x01(\x01:\x03\x34.5\x12\x1e\n\x10max_deceleration\x18= \x01(\x01:\x04-4.5\x12\x1b\n\x10safe_time_buffer\x18\x46 \x01(\x01:\x01\x33\x12\x19\n\rsafe_distance\x18G \x01(\x01:\x02\x32\x30\x12$\n\x19spatial_potential_penalty\x18P \x01(\x01:\x01\x31\x12\x1f\n\x10is_lane_changing\x18Q \x01(\x08:\x05\x66\x61lse')
)




_SPEEDHEURISTICCONFIG = _descriptor.Descriptor(
  name='SpeedHeuristicConfig',
  full_name='apollo.planning.SpeedHeuristicConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default_speed_config', full_name='apollo.planning.SpeedHeuristicConfig.default_speed_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_change_speed_config', full_name='apollo.planning.SpeedHeuristicConfig.lane_change_speed_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=223,
)


_DPSTSPEEDCONFIG = _descriptor.Descriptor(
  name='DpStSpeedConfig',
  full_name='apollo.planning.DpStSpeedConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit_t', full_name='apollo.planning.DpStSpeedConfig.unit_t', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dense_dimension_s', full_name='apollo.planning.DpStSpeedConfig.dense_dimension_s', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=41,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dense_unit_s', full_name='apollo.planning.DpStSpeedConfig.dense_unit_s', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparse_unit_s', full_name='apollo.planning.DpStSpeedConfig.sparse_unit_s', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_weight', full_name='apollo.planning.DpStSpeedConfig.speed_weight', index=4,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel_weight', full_name='apollo.planning.DpStSpeedConfig.accel_weight', index=5,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jerk_weight', full_name='apollo.planning.DpStSpeedConfig.jerk_weight', index=6,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_weight', full_name='apollo.planning.DpStSpeedConfig.obstacle_weight', index=7,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_weight', full_name='apollo.planning.DpStSpeedConfig.reference_weight', index=8,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='go_down_buffer', full_name='apollo.planning.DpStSpeedConfig.go_down_buffer', index=9,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='go_up_buffer', full_name='apollo.planning.DpStSpeedConfig.go_up_buffer', index=10,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_obstacle_cost', full_name='apollo.planning.DpStSpeedConfig.default_obstacle_cost', index=11,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10000000000),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_speed_cost', full_name='apollo.planning.DpStSpeedConfig.default_speed_cost', index=12,
      number=31, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exceed_speed_penalty', full_name='apollo.planning.DpStSpeedConfig.exceed_speed_penalty', index=13,
      number=32, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_speed_penalty', full_name='apollo.planning.DpStSpeedConfig.low_speed_penalty', index=14,
      number=33, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_speed_penalty', full_name='apollo.planning.DpStSpeedConfig.reference_speed_penalty', index=15,
      number=34, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_clear_low_speed_penalty', full_name='apollo.planning.DpStSpeedConfig.keep_clear_low_speed_penalty', index=16,
      number=35, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel_penalty', full_name='apollo.planning.DpStSpeedConfig.accel_penalty', index=17,
      number=40, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decel_penalty', full_name='apollo.planning.DpStSpeedConfig.decel_penalty', index=18,
      number=41, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='positive_jerk_coeff', full_name='apollo.planning.DpStSpeedConfig.positive_jerk_coeff', index=19,
      number=50, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='negative_jerk_coeff', full_name='apollo.planning.DpStSpeedConfig.negative_jerk_coeff', index=20,
      number=51, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(300),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_acceleration', full_name='apollo.planning.DpStSpeedConfig.max_acceleration', index=21,
      number=60, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(4.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_deceleration', full_name='apollo.planning.DpStSpeedConfig.max_deceleration', index=22,
      number=61, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(-4.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='safe_time_buffer', full_name='apollo.planning.DpStSpeedConfig.safe_time_buffer', index=23,
      number=70, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='safe_distance', full_name='apollo.planning.DpStSpeedConfig.safe_distance', index=24,
      number=71, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(20),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spatial_potential_penalty', full_name='apollo.planning.DpStSpeedConfig.spatial_potential_penalty', index=25,
      number=80, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_lane_changing', full_name='apollo.planning.DpStSpeedConfig.is_lane_changing', index=26,
      number=81, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=1058,
)

_SPEEDHEURISTICCONFIG.fields_by_name['default_speed_config'].message_type = _DPSTSPEEDCONFIG
_SPEEDHEURISTICCONFIG.fields_by_name['lane_change_speed_config'].message_type = _DPSTSPEEDCONFIG
DESCRIPTOR.message_types_by_name['SpeedHeuristicConfig'] = _SPEEDHEURISTICCONFIG
DESCRIPTOR.message_types_by_name['DpStSpeedConfig'] = _DPSTSPEEDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeedHeuristicConfig = _reflection.GeneratedProtocolMessageType('SpeedHeuristicConfig', (_message.Message,), dict(
  DESCRIPTOR = _SPEEDHEURISTICCONFIG,
  __module__ = 'modules.planning.proto.dp_st_speed_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.SpeedHeuristicConfig)
  ))
_sym_db.RegisterMessage(SpeedHeuristicConfig)

DpStSpeedConfig = _reflection.GeneratedProtocolMessageType('DpStSpeedConfig', (_message.Message,), dict(
  DESCRIPTOR = _DPSTSPEEDCONFIG,
  __module__ = 'modules.planning.proto.dp_st_speed_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.DpStSpeedConfig)
  ))
_sym_db.RegisterMessage(DpStSpeedConfig)


# @@protoc_insertion_point(module_scope)
