# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/lane_change_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/lane_change_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n7modules/planning/proto/lane_change_decider_config.proto\x12\x0f\x61pollo.planning\"\x97\x02\n\x17LaneChangeDeciderConfig\x12(\n enable_lane_change_urgency_check\x18\x01 \x01(\x08\x12,\n\x1d\x65nable_prioritize_change_lane\x18\x02 \x01(\x08:\x05\x66\x61lse\x12(\n\x19\x65nable_remove_change_lane\x18\x03 \x01(\x08:\x05\x66\x61lse\x12#\n\x14reckless_change_lane\x18\x04 \x01(\x08:\x05\x66\x61lse\x12,\n\x1f\x63hange_lane_success_freeze_time\x18\x05 \x01(\x01:\x03\x31.5\x12\'\n\x1c\x63hange_lane_fail_freeze_time\x18\x06 \x01(\x01:\x01\x31')
)




_LANECHANGEDECIDERCONFIG = _descriptor.Descriptor(
  name='LaneChangeDeciderConfig',
  full_name='apollo.planning.LaneChangeDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_lane_change_urgency_check', full_name='apollo.planning.LaneChangeDeciderConfig.enable_lane_change_urgency_check', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_prioritize_change_lane', full_name='apollo.planning.LaneChangeDeciderConfig.enable_prioritize_change_lane', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_remove_change_lane', full_name='apollo.planning.LaneChangeDeciderConfig.enable_remove_change_lane', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reckless_change_lane', full_name='apollo.planning.LaneChangeDeciderConfig.reckless_change_lane', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change_lane_success_freeze_time', full_name='apollo.planning.LaneChangeDeciderConfig.change_lane_success_freeze_time', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change_lane_fail_freeze_time', full_name='apollo.planning.LaneChangeDeciderConfig.change_lane_fail_freeze_time', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=356,
)

DESCRIPTOR.message_types_by_name['LaneChangeDeciderConfig'] = _LANECHANGEDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaneChangeDeciderConfig = _reflection.GeneratedProtocolMessageType('LaneChangeDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _LANECHANGEDECIDERCONFIG,
  __module__ = 'modules.planning.proto.lane_change_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.LaneChangeDeciderConfig)
  ))
_sym_db.RegisterMessage(LaneChangeDeciderConfig)


# @@protoc_insertion_point(module_scope)
