# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/navi_path_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/navi_path_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n5modules/planning/proto/navi_path_decider_config.proto\x12\x0f\x61pollo.planning\"\xd5\x03\n\x15NaviPathDeciderConfig\x12\x1a\n\x0fmin_path_length\x18\x01 \x01(\x01:\x01\x35\x12 \n\x15min_look_forward_time\x18\x02 \x01(\r:\x01\x32\x12#\n\x16max_keep_lane_distance\x18\x03 \x01(\x01:\x03\x30.8\x12!\n\x15max_keep_lane_shift_y\x18\x04 \x01(\x01:\x02\x32\x30\x12 \n\x14min_keep_lane_offset\x18\x05 \x01(\x01:\x02\x31\x35\x12*\n\x1ckeep_lane_shift_compensation\x18\x06 \x01(\x01:\x04\x30.01\x12M\n\x1bmove_dest_lane_config_talbe\x18\x07 \x01(\x0b\x32(.apollo.planning.MoveDestLaneConfigTable\x12)\n\x1bmove_dest_lane_compensation\x18\x08 \x01(\x01:\x04\x30.35\x12\x1e\n\x13max_kappa_threshold\x18\t \x01(\x01:\x01\x30\x12,\n!kappa_move_dest_lane_compensation\x18\n \x01(\x01:\x01\x30\x12 \n\x15start_plan_point_from\x18\x0b \x01(\r:\x01\x30\"N\n\x17MoveDestLaneConfigTable\x12\x33\n\rlateral_shift\x18\x01 \x03(\x0b\x32\x1c.apollo.planning.ShiftConfig\"O\n\x0bShiftConfig\x12\x17\n\tmax_speed\x18\x01 \x01(\x01:\x04\x34.16\x12\'\n\x1amax_move_dest_lane_shift_y\x18\x03 \x01(\x01:\x03\x30.4')
)




_NAVIPATHDECIDERCONFIG = _descriptor.Descriptor(
  name='NaviPathDeciderConfig',
  full_name='apollo.planning.NaviPathDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_path_length', full_name='apollo.planning.NaviPathDeciderConfig.min_path_length', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_look_forward_time', full_name='apollo.planning.NaviPathDeciderConfig.min_look_forward_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_keep_lane_distance', full_name='apollo.planning.NaviPathDeciderConfig.max_keep_lane_distance', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.8),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_keep_lane_shift_y', full_name='apollo.planning.NaviPathDeciderConfig.max_keep_lane_shift_y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(20),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_keep_lane_offset', full_name='apollo.planning.NaviPathDeciderConfig.min_keep_lane_offset', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(15),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_lane_shift_compensation', full_name='apollo.planning.NaviPathDeciderConfig.keep_lane_shift_compensation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.01),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move_dest_lane_config_talbe', full_name='apollo.planning.NaviPathDeciderConfig.move_dest_lane_config_talbe', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move_dest_lane_compensation', full_name='apollo.planning.NaviPathDeciderConfig.move_dest_lane_compensation', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.35),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_kappa_threshold', full_name='apollo.planning.NaviPathDeciderConfig.max_kappa_threshold', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kappa_move_dest_lane_compensation', full_name='apollo.planning.NaviPathDeciderConfig.kappa_move_dest_lane_compensation', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_plan_point_from', full_name='apollo.planning.NaviPathDeciderConfig.start_plan_point_from', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=544,
)


_MOVEDESTLANECONFIGTABLE = _descriptor.Descriptor(
  name='MoveDestLaneConfigTable',
  full_name='apollo.planning.MoveDestLaneConfigTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lateral_shift', full_name='apollo.planning.MoveDestLaneConfigTable.lateral_shift', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=624,
)


_SHIFTCONFIG = _descriptor.Descriptor(
  name='ShiftConfig',
  full_name='apollo.planning.ShiftConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_speed', full_name='apollo.planning.ShiftConfig.max_speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(4.16),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_move_dest_lane_shift_y', full_name='apollo.planning.ShiftConfig.max_move_dest_lane_shift_y', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=705,
)

_NAVIPATHDECIDERCONFIG.fields_by_name['move_dest_lane_config_talbe'].message_type = _MOVEDESTLANECONFIGTABLE
_MOVEDESTLANECONFIGTABLE.fields_by_name['lateral_shift'].message_type = _SHIFTCONFIG
DESCRIPTOR.message_types_by_name['NaviPathDeciderConfig'] = _NAVIPATHDECIDERCONFIG
DESCRIPTOR.message_types_by_name['MoveDestLaneConfigTable'] = _MOVEDESTLANECONFIGTABLE
DESCRIPTOR.message_types_by_name['ShiftConfig'] = _SHIFTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NaviPathDeciderConfig = _reflection.GeneratedProtocolMessageType('NaviPathDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _NAVIPATHDECIDERCONFIG,
  __module__ = 'modules.planning.proto.navi_path_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.NaviPathDeciderConfig)
  ))
_sym_db.RegisterMessage(NaviPathDeciderConfig)

MoveDestLaneConfigTable = _reflection.GeneratedProtocolMessageType('MoveDestLaneConfigTable', (_message.Message,), dict(
  DESCRIPTOR = _MOVEDESTLANECONFIGTABLE,
  __module__ = 'modules.planning.proto.navi_path_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.MoveDestLaneConfigTable)
  ))
_sym_db.RegisterMessage(MoveDestLaneConfigTable)

ShiftConfig = _reflection.GeneratedProtocolMessageType('ShiftConfig', (_message.Message,), dict(
  DESCRIPTOR = _SHIFTCONFIG,
  __module__ = 'modules.planning.proto.navi_path_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.ShiftConfig)
  ))
_sym_db.RegisterMessage(ShiftConfig)


# @@protoc_insertion_point(module_scope)
