# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/navi_speed_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/navi_speed_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n6modules/planning/proto/navi_speed_decider_config.proto\x12\x0f\x61pollo.planning\"\xd2\x04\n\x16NaviSpeedDeciderConfig\x12\x1a\n\x0fpreferred_accel\x18\x01 \x01(\x01:\x01\x32\x12\x1a\n\x0fpreferred_decel\x18\x02 \x01(\x01:\x01\x32\x12\x19\n\x0epreferred_jerk\x18\x03 \x01(\x01:\x01\x32\x12\x14\n\tmax_accel\x18\x04 \x01(\x01:\x01\x34\x12\x14\n\tmax_decel\x18\x05 \x01(\x01:\x01\x35\x12\x1c\n\x0fobstacle_buffer\x18\x06 \x01(\x01:\x03\x30.5\x12\x1d\n\x12safe_distance_base\x18\x07 \x01(\x01:\x01\x32\x12\x1e\n\x13safe_distance_ratio\x18\x08 \x01(\x01:\x01\x31\x12\"\n\x15\x66ollowing_accel_ratio\x18\t \x01(\x01:\x03\x30.5\x12%\n\x18soft_centric_accel_limit\x18\n \x01(\x01:\x03\x31.2\x12%\n\x18hard_centric_accel_limit\x18\x0b \x01(\x01:\x03\x31.5\x12\x1d\n\x10hard_speed_limit\x18\x0c \x01(\x01:\x03\x31\x30\x30\x12\x1c\n\x10hard_accel_limit\x18\r \x01(\x01:\x02\x31\x30\x12\x1e\n\x10\x65nable_safe_path\x18\x0e \x01(\x08:\x04true\x12)\n\x1b\x65nable_planning_start_point\x18\x0f \x01(\x08:\x04true\x12,\n\x1e\x65nable_accel_auto_compensation\x18\x10 \x01(\x08:\x04true\x12\x18\n\rkappa_preview\x18\x11 \x01(\x01:\x01\x30\x12\x1a\n\x0fkappa_threshold\x18\x12 \x01(\x01:\x01\x30')
)




_NAVISPEEDDECIDERCONFIG = _descriptor.Descriptor(
  name='NaviSpeedDeciderConfig',
  full_name='apollo.planning.NaviSpeedDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preferred_accel', full_name='apollo.planning.NaviSpeedDeciderConfig.preferred_accel', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preferred_decel', full_name='apollo.planning.NaviSpeedDeciderConfig.preferred_decel', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preferred_jerk', full_name='apollo.planning.NaviSpeedDeciderConfig.preferred_jerk', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_accel', full_name='apollo.planning.NaviSpeedDeciderConfig.max_accel', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_decel', full_name='apollo.planning.NaviSpeedDeciderConfig.max_decel', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_buffer', full_name='apollo.planning.NaviSpeedDeciderConfig.obstacle_buffer', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='safe_distance_base', full_name='apollo.planning.NaviSpeedDeciderConfig.safe_distance_base', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='safe_distance_ratio', full_name='apollo.planning.NaviSpeedDeciderConfig.safe_distance_ratio', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='following_accel_ratio', full_name='apollo.planning.NaviSpeedDeciderConfig.following_accel_ratio', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soft_centric_accel_limit', full_name='apollo.planning.NaviSpeedDeciderConfig.soft_centric_accel_limit', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hard_centric_accel_limit', full_name='apollo.planning.NaviSpeedDeciderConfig.hard_centric_accel_limit', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hard_speed_limit', full_name='apollo.planning.NaviSpeedDeciderConfig.hard_speed_limit', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(100),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hard_accel_limit', full_name='apollo.planning.NaviSpeedDeciderConfig.hard_accel_limit', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_safe_path', full_name='apollo.planning.NaviSpeedDeciderConfig.enable_safe_path', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_planning_start_point', full_name='apollo.planning.NaviSpeedDeciderConfig.enable_planning_start_point', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_accel_auto_compensation', full_name='apollo.planning.NaviSpeedDeciderConfig.enable_accel_auto_compensation', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kappa_preview', full_name='apollo.planning.NaviSpeedDeciderConfig.kappa_preview', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kappa_threshold', full_name='apollo.planning.NaviSpeedDeciderConfig.kappa_threshold', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=670,
)

DESCRIPTOR.message_types_by_name['NaviSpeedDeciderConfig'] = _NAVISPEEDDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NaviSpeedDeciderConfig = _reflection.GeneratedProtocolMessageType('NaviSpeedDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _NAVISPEEDDECIDERCONFIG,
  __module__ = 'modules.planning.proto.navi_speed_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.NaviSpeedDeciderConfig)
  ))
_sym_db.RegisterMessage(NaviSpeedDeciderConfig)


# @@protoc_insertion_point(module_scope)
