# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/open_space_roi_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/open_space_roi_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n:modules/planning/proto/open_space_roi_decider_config.proto\x12\x0f\x61pollo.planning\"\xc8\x05\n\x19OpenSpaceRoiDeciderConfig\x12\x44\n\x08roi_type\x18\x01 \x01(\x0e\x32\x32.apollo.planning.OpenSpaceRoiDeciderConfig.RoiType\x12(\n\x1croi_longitudinal_range_start\x18\x02 \x01(\x01:\x02\x31\x30\x12&\n\x1aroi_longitudinal_range_end\x18\x03 \x01(\x01:\x02\x31\x30\x12\x1e\n\x13parking_start_range\x18\x04 \x01(\x01:\x01\x37\x12\x1e\n\x0fparking_inwards\x18\x05 \x01(\x08:\x05\x66\x61lse\x12#\n\x1b\x65nable_perception_obstacles\x18\x06 \x01(\x08\x12!\n\x14parking_depth_buffer\x18\x07 \x01(\x01:\x03\x30.1\x12\'\n\x1aroi_line_segment_min_angle\x18\x08 \x01(\x01:\x03\x30.3\x12\"\n\x17roi_line_segment_length\x18\t \x01(\x01:\x01\x31\x12,\n roi_line_segment_length_from_map\x18\n \x01(\x01:\x02\x31\x30\x12\x34\n&perception_obstacle_filtering_distance\x18\x0b \x01(\x01:\x04\x31\x30\x30\x30\x12\"\n\x1aperception_obstacle_buffer\x18\x0c \x01(\x01\x12\x32\n\'curb_heading_tangent_change_upper_limit\x18\r \x01(\x01:\x01\x31\x12\x1f\n\x13\x65nd_pose_s_distance\x18\x0e \x01(\x01:\x02\x31\x30\"a\n\x07RoiType\x12\x0f\n\x0bNOT_DEFINED\x10\x00\x12\x0b\n\x07PARKING\x10\x01\x12\r\n\tPULL_OVER\x10\x02\x12\x0f\n\x0bPARK_AND_GO\x10\x03\x12\x18\n\x14NARROW_STREET_U_TURN\x10\x04')
)



_OPENSPACEROIDECIDERCONFIG_ROITYPE = _descriptor.EnumDescriptor(
  name='RoiType',
  full_name='apollo.planning.OpenSpaceRoiDeciderConfig.RoiType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_DEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARKING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PULL_OVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARK_AND_GO', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NARROW_STREET_U_TURN', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=695,
  serialized_end=792,
)
_sym_db.RegisterEnumDescriptor(_OPENSPACEROIDECIDERCONFIG_ROITYPE)


_OPENSPACEROIDECIDERCONFIG = _descriptor.Descriptor(
  name='OpenSpaceRoiDeciderConfig',
  full_name='apollo.planning.OpenSpaceRoiDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roi_type', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.roi_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_longitudinal_range_start', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.roi_longitudinal_range_start', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_longitudinal_range_end', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.roi_longitudinal_range_end', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parking_start_range', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.parking_start_range', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(7),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parking_inwards', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.parking_inwards', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_perception_obstacles', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.enable_perception_obstacles', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parking_depth_buffer', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.parking_depth_buffer', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_line_segment_min_angle', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.roi_line_segment_min_angle', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_line_segment_length', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.roi_line_segment_length', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_line_segment_length_from_map', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.roi_line_segment_length_from_map', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='perception_obstacle_filtering_distance', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.perception_obstacle_filtering_distance', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1000),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='perception_obstacle_buffer', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.perception_obstacle_buffer', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='curb_heading_tangent_change_upper_limit', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.curb_heading_tangent_change_upper_limit', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_pose_s_distance', full_name='apollo.planning.OpenSpaceRoiDeciderConfig.end_pose_s_distance', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPENSPACEROIDECIDERCONFIG_ROITYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=792,
)

_OPENSPACEROIDECIDERCONFIG.fields_by_name['roi_type'].enum_type = _OPENSPACEROIDECIDERCONFIG_ROITYPE
_OPENSPACEROIDECIDERCONFIG_ROITYPE.containing_type = _OPENSPACEROIDECIDERCONFIG
DESCRIPTOR.message_types_by_name['OpenSpaceRoiDeciderConfig'] = _OPENSPACEROIDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenSpaceRoiDeciderConfig = _reflection.GeneratedProtocolMessageType('OpenSpaceRoiDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _OPENSPACEROIDECIDERCONFIG,
  __module__ = 'modules.planning.proto.open_space_roi_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.OpenSpaceRoiDeciderConfig)
  ))
_sym_db.RegisterMessage(OpenSpaceRoiDeciderConfig)


# @@protoc_insertion_point(module_scope)
