# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/open_space_pre_stop_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/open_space_pre_stop_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n?modules/planning/proto/open_space_pre_stop_decider_config.proto\x12\x0f\x61pollo.planning\"\x86\x02\n\x1dOpenSpacePreStopDeciderConfig\x12J\n\tstop_type\x18\x01 \x01(\x0e\x32\x37.apollo.planning.OpenSpacePreStopDeciderConfig.StopType\x12\"\n\x17rightaway_stop_distance\x18\x02 \x01(\x01:\x01\x32\x12\"\n\x17stop_distance_to_target\x18\x03 \x01(\x01:\x01\x35\"Q\n\x08StopType\x12\x0f\n\x0bNOT_DEFINED\x10\x00\x12\x0b\n\x07PARKING\x10\x01\x12\r\n\tPULL_OVER\x10\x02\x12\x18\n\x14NARROW_STREET_U_TURN\x10\x03')
)



_OPENSPACEPRESTOPDECIDERCONFIG_STOPTYPE = _descriptor.EnumDescriptor(
  name='StopType',
  full_name='apollo.planning.OpenSpacePreStopDeciderConfig.StopType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_DEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARKING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PULL_OVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NARROW_STREET_U_TURN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=266,
  serialized_end=347,
)
_sym_db.RegisterEnumDescriptor(_OPENSPACEPRESTOPDECIDERCONFIG_STOPTYPE)


_OPENSPACEPRESTOPDECIDERCONFIG = _descriptor.Descriptor(
  name='OpenSpacePreStopDeciderConfig',
  full_name='apollo.planning.OpenSpacePreStopDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stop_type', full_name='apollo.planning.OpenSpacePreStopDeciderConfig.stop_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightaway_stop_distance', full_name='apollo.planning.OpenSpacePreStopDeciderConfig.rightaway_stop_distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_distance_to_target', full_name='apollo.planning.OpenSpacePreStopDeciderConfig.stop_distance_to_target', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPENSPACEPRESTOPDECIDERCONFIG_STOPTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=347,
)

_OPENSPACEPRESTOPDECIDERCONFIG.fields_by_name['stop_type'].enum_type = _OPENSPACEPRESTOPDECIDERCONFIG_STOPTYPE
_OPENSPACEPRESTOPDECIDERCONFIG_STOPTYPE.containing_type = _OPENSPACEPRESTOPDECIDERCONFIG
DESCRIPTOR.message_types_by_name['OpenSpacePreStopDeciderConfig'] = _OPENSPACEPRESTOPDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenSpacePreStopDeciderConfig = _reflection.GeneratedProtocolMessageType('OpenSpacePreStopDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _OPENSPACEPRESTOPDECIDERCONFIG,
  __module__ = 'modules.planning.proto.open_space_pre_stop_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.OpenSpacePreStopDeciderConfig)
  ))
_sym_db.RegisterMessage(OpenSpacePreStopDeciderConfig)


# @@protoc_insertion_point(module_scope)
