# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/path_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/path_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n0modules/planning/proto/path_decider_config.proto\x12\x0f\x61pollo.planning\"8\n\x11PathDeciderConfig\x12#\n\x16static_obstacle_buffer\x18\x01 \x01(\x01:\x03\x30.3')
)




_PATHDECIDERCONFIG = _descriptor.Descriptor(
  name='PathDeciderConfig',
  full_name='apollo.planning.PathDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='static_obstacle_buffer', full_name='apollo.planning.PathDeciderConfig.static_obstacle_buffer', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['PathDeciderConfig'] = _PATHDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathDeciderConfig = _reflection.GeneratedProtocolMessageType('PathDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _PATHDECIDERCONFIG,
  __module__ = 'modules.planning.proto.path_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.PathDeciderConfig)
  ))
_sym_db.RegisterMessage(PathDeciderConfig)


# @@protoc_insertion_point(module_scope)
