# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/rule_based_stop_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/rule_based_stop_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n;modules/planning/proto/rule_based_stop_decider_config.proto\x12\x0f\x61pollo.planning\"\xce\x02\n\x1aRuleBasedStopDeciderConfig\x12\x1f\n\x12max_adc_stop_speed\x18\x01 \x01(\x01:\x03\x30.3\x12$\n\x17max_valid_stop_distance\x18\x02 \x01(\x01:\x03\x30.5\x12\x1d\n\x12search_beam_length\x18\x03 \x01(\x01:\x01\x35\x12*\n\x1csearch_beam_radius_intensity\x18\x04 \x01(\x01:\x04\x30.08\x12\x1a\n\x0csearch_range\x18\x05 \x01(\x01:\x04\x33.14\x12&\n\x18is_block_angle_threshold\x18\x06 \x01(\x01:\x04\x31.57\x12-\n!approach_distance_for_lane_change\x18\n \x01(\x01:\x02\x38\x30\x12+\n\x1furgent_distance_for_lane_change\x18\x0b \x01(\x01:\x02\x35\x30')
)




_RULEBASEDSTOPDECIDERCONFIG = _descriptor.Descriptor(
  name='RuleBasedStopDeciderConfig',
  full_name='apollo.planning.RuleBasedStopDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_adc_stop_speed', full_name='apollo.planning.RuleBasedStopDeciderConfig.max_adc_stop_speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_valid_stop_distance', full_name='apollo.planning.RuleBasedStopDeciderConfig.max_valid_stop_distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_beam_length', full_name='apollo.planning.RuleBasedStopDeciderConfig.search_beam_length', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_beam_radius_intensity', full_name='apollo.planning.RuleBasedStopDeciderConfig.search_beam_radius_intensity', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.08),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_range', full_name='apollo.planning.RuleBasedStopDeciderConfig.search_range', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(3.14),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_block_angle_threshold', full_name='apollo.planning.RuleBasedStopDeciderConfig.is_block_angle_threshold', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1.57),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='approach_distance_for_lane_change', full_name='apollo.planning.RuleBasedStopDeciderConfig.approach_distance_for_lane_change', index=6,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(80),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='urgent_distance_for_lane_change', full_name='apollo.planning.RuleBasedStopDeciderConfig.urgent_distance_for_lane_change', index=7,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(50),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=415,
)

DESCRIPTOR.message_types_by_name['RuleBasedStopDeciderConfig'] = _RULEBASEDSTOPDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RuleBasedStopDeciderConfig = _reflection.GeneratedProtocolMessageType('RuleBasedStopDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _RULEBASEDSTOPDECIDERCONFIG,
  __module__ = 'modules.planning.proto.rule_based_stop_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.RuleBasedStopDeciderConfig)
  ))
_sym_db.RegisterMessage(RuleBasedStopDeciderConfig)


# @@protoc_insertion_point(module_scope)
