# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/speed_bounds_decider_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/speed_bounds_decider_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n8modules/planning/proto/speed_bounds_decider_config.proto\x12\x0f\x61pollo.planning\"\xbf\x02\n\x18SpeedBoundsDeciderConfig\x12\x15\n\ntotal_time\x18\x01 \x01(\x01:\x01\x37\x12\x1c\n\x0f\x62oundary_buffer\x18\x02 \x01(\x01:\x03\x30.1\x12)\n\x1emax_centric_acceleration_limit\x18\x03 \x01(\x01:\x01\x32\x12\x1c\n\rminimal_kappa\x18\x04 \x01(\x01:\x05\x31\x65-05\x12\x1a\n\x0fpoint_extension\x18\x05 \x01(\x01:\x01\x31\x12\x19\n\x0clowest_speed\x18\x06 \x01(\x01:\x03\x32.5\x12!\n\x16\x63ollision_safety_range\x18\x07 \x01(\x01:\x01\x31\x12$\n\x1cstatic_obs_nudge_speed_ratio\x18\x08 \x01(\x01\x12%\n\x1d\x64ynamic_obs_nudge_speed_ratio\x18\t \x01(\x01')
)




_SPEEDBOUNDSDECIDERCONFIG = _descriptor.Descriptor(
  name='SpeedBoundsDeciderConfig',
  full_name='apollo.planning.SpeedBoundsDeciderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_time', full_name='apollo.planning.SpeedBoundsDeciderConfig.total_time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(7),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boundary_buffer', full_name='apollo.planning.SpeedBoundsDeciderConfig.boundary_buffer', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_centric_acceleration_limit', full_name='apollo.planning.SpeedBoundsDeciderConfig.max_centric_acceleration_limit', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimal_kappa', full_name='apollo.planning.SpeedBoundsDeciderConfig.minimal_kappa', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1e-05),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_extension', full_name='apollo.planning.SpeedBoundsDeciderConfig.point_extension', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowest_speed', full_name='apollo.planning.SpeedBoundsDeciderConfig.lowest_speed', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collision_safety_range', full_name='apollo.planning.SpeedBoundsDeciderConfig.collision_safety_range', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='static_obs_nudge_speed_ratio', full_name='apollo.planning.SpeedBoundsDeciderConfig.static_obs_nudge_speed_ratio', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dynamic_obs_nudge_speed_ratio', full_name='apollo.planning.SpeedBoundsDeciderConfig.dynamic_obs_nudge_speed_ratio', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=397,
)

DESCRIPTOR.message_types_by_name['SpeedBoundsDeciderConfig'] = _SPEEDBOUNDSDECIDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeedBoundsDeciderConfig = _reflection.GeneratedProtocolMessageType('SpeedBoundsDeciderConfig', (_message.Message,), dict(
  DESCRIPTOR = _SPEEDBOUNDSDECIDERCONFIG,
  __module__ = 'modules.planning.proto.speed_bounds_decider_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.SpeedBoundsDeciderConfig)
  ))
_sym_db.RegisterMessage(SpeedBoundsDeciderConfig)


# @@protoc_insertion_point(module_scope)
